// AUTO-GENERATED by scripts/generate-version.mjs — do not edit
export const BUILD_INFO = {
  "version": "0.1.27",
  "baseVersion": "0.1.0",
  "versionEpoch": "2026-08-26",
  "uniqueDays": 28,
  "commitsToday": 18,
  "sha": "90d491c"
} as const;
