// AUTO-GENERATED by scripts/generate-version.mjs — do not edit
export const BUILD_INFO = {
  "version": "0.1.21",
  "baseVersion": "0.1.0",
  "versionEpoch": "2026-08-26",
  "uniqueDays": 22,
  "commitsToday": 7,
  "sha": "a62982f"
} as const;
