// AUTO-GENERATED by scripts/generate-version.mjs — do not edit
export const BUILD_INFO = {
  "version": "0.1.18",
  "baseVersion": "0.1.0",
  "versionEpoch": "2026-08-26",
  "uniqueDays": 19,
  "commitsToday": 1,
  "sha": "01e5845"
} as const;
