/**
 * Builds APP version from package.json semver + today's git commit count.
 * Each commit since local midnight bumps the patch segment by one.
 */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function git(cmd) {
  try {
    return execSync(cmd, {
      cwd: repoRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

const pkg = JSON.parse(fs.readFileSync(path.join(repoRoot, "package.json"), "utf8"));
const baseVersion = pkg.version;
const [major, minor, patch = "0"] = baseVersion.split(".");

const now = new Date();
const since =
  `${now.getFullYear()}-` +
  `${String(now.getMonth() + 1).padStart(2, "0")}-` +
  `${String(now.getDate()).padStart(2, "0")} 00:00:00`;

const commitsToday = parseInt(git(`git rev-list --count --since="${since}" HEAD`) || "0", 10);
const sha = (git("git rev-parse --short HEAD") || "unknown").slice(0, 7);
const version = `${major}.${minor}.${parseInt(patch, 10) + commitsToday}`;

const buildInfo = { version, baseVersion, commitsToday, sha };

const target = path.join(repoRoot, "packages", "shared", "src", "buildInfo.ts");
fs.writeFileSync(
  target,
  "// AUTO-GENERATED by scripts/generate-version.mjs — do not edit\n" +
    `export const BUILD_INFO = ${JSON.stringify(buildInfo, null, 2)} as const;\n`,
);

console.log(`Version: ${version} (${commitsToday} commit(s) today, ${sha})`);
