/**
 * Builds APP version from package.json semver + today's git commit count.
 * Each commit since local midnight bumps the patch segment by one.
 * With --record-release, appends new versions to VERSIONS.md during production builds.
 */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  formatReleaseDate,
  parseVersionsMarkdown,
  renderVersionsMarkdown,
  upsertReleaseEntry,
} from "./versionHistory.mjs";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const VERSIONS_FILE = path.join(repoRoot, "VERSIONS.md");
const recordRelease = process.argv.includes("--record-release");

function git(cmd) {
  try {
    return execSync(cmd, {
      cwd: repoRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

function readVersionsFile() {
  if (!fs.existsSync(VERSIONS_FILE)) {
    return [];
  }
  return parseVersionsMarkdown(fs.readFileSync(VERSIONS_FILE, "utf8"));
}

function writeVersionsFile(entries) {
  fs.writeFileSync(VERSIONS_FILE, renderVersionsMarkdown(entries));
}

function recordVersionRelease(version, date) {
  const released = formatReleaseDate(date);
  const next = upsertReleaseEntry(readVersionsFile(), version, released);
  writeVersionsFile(next);
  return released;
}

const pkg = JSON.parse(fs.readFileSync(path.join(repoRoot, "package.json"), "utf8"));
const baseVersion = pkg.version;
const [major, minor, patch = "0"] = baseVersion.split(".");

const now = new Date();
const since =
  `${now.getFullYear()}-` +
  `${String(now.getMonth() + 1).padStart(2, "0")}-` +
  `${String(now.getDate()).padStart(2, "0")} 00:00:00`;

const commitsToday = parseInt(git(`git rev-list --count --since="${since}" HEAD`) || "0", 10);
const sha = (git("git rev-parse --short HEAD") || "unknown").slice(0, 7);
const version = `${major}.${minor}.${parseInt(patch, 10) + commitsToday}`;

const buildInfo = { version, baseVersion, commitsToday, sha };

const target = path.join(repoRoot, "packages", "shared", "src", "buildInfo.ts");
fs.writeFileSync(
  target,
  "// AUTO-GENERATED by scripts/generate-version.mjs — do not edit\n" +
    `export const BUILD_INFO = ${JSON.stringify(buildInfo, null, 2)} as const;\n`,
);

function updateReadmeVersion(filePath, pattern, line) {
  const abs = path.join(repoRoot, filePath);
  const text = fs.readFileSync(abs, "utf8");
  if (!pattern.test(text)) {
    throw new Error(`Version line not found in ${filePath}`);
  }
  const next = text.replace(pattern, line);
  if (next !== text) {
    fs.writeFileSync(abs, next);
  }
}

updateReadmeVersion("README.md", /\*\*Current version:\*\* \d+\.\d+\.\d+/, `**Current version:** ${version}`);
updateReadmeVersion(
  "readme-ru.md",
  /\*\*Актуальная версия:\*\* \d+\.\d+\.\d+/,
  `**Актуальная версия:** ${version}`,
);

if (recordRelease) {
  const before = readVersionsFile();
  const released = recordVersionRelease(version, now);
  const added = !before.some((entry) => entry.version === version);
  if (added) {
    console.log(`Recorded release ${version} (${released}) in VERSIONS.md`);
  }
}

console.log(`Version: ${version} (${commitsToday} commit(s) today, ${sha})`);
