/**
 * App version from git history: +0.0.1 per calendar day that has a commit (since versionEpoch).
 * Same revision ⇒ same version on every machine. Local dev/build does not bump.
 * --record-release rewrites VERSIONS.md from git (for a commit you intend to push).
 */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  computeAppVersion,
  DEFAULT_VERSION_EPOCH,
  releaseEntriesFromCommitDates,
  renderVersionsMarkdown,
} from "./versionHistory.mjs";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const VERSIONS_FILE = path.join(repoRoot, "VERSIONS.md");
const recordRelease = process.argv.includes("--record-release");

function git(cmd) {
  try {
    return execSync(cmd, {
      cwd: repoRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

const pkg = JSON.parse(fs.readFileSync(path.join(repoRoot, "package.json"), "utf8"));
const baseVersion = pkg.version;
const versionEpoch =
  typeof pkg.versionEpoch === "string" && /^\d{4}-\d{2}-\d{2}$/.test(pkg.versionEpoch)
    ? pkg.versionEpoch
    : DEFAULT_VERSION_EPOCH;

const now = new Date();
const since =
  `${now.getFullYear()}-` +
  `${String(now.getMonth() + 1).padStart(2, "0")}-` +
  `${String(now.getDate()).padStart(2, "0")} 00:00:00`;

const commitsToday = parseInt(git(`git rev-list --count --since="${since}" HEAD`) || "0", 10);
const commitDates = git("git log --format=%as HEAD").split("\n").filter(Boolean);
const { version, uniqueDays } = computeAppVersion({
  baseVersion,
  commitDates,
  epochDate: versionEpoch,
});
const sha = (git("git rev-parse --short HEAD") || "unknown").slice(0, 7);

const buildInfo = { version, baseVersion, versionEpoch, uniqueDays, commitsToday, sha };

const target = path.join(repoRoot, "packages", "shared", "src", "buildInfo.ts");
fs.writeFileSync(
  target,
  "// AUTO-GENERATED by scripts/generate-version.mjs — do not edit\n" +
    `export const BUILD_INFO = ${JSON.stringify(buildInfo, null, 2)} as const;\n`,
);

function updateReadmeVersion(filePath, pattern, line) {
  const abs = path.join(repoRoot, filePath);
  const text = fs.readFileSync(abs, "utf8");
  if (!pattern.test(text)) {
    throw new Error(`Version line not found in ${filePath}`);
  }
  const next = text.replace(pattern, line);
  if (next !== text) {
    fs.writeFileSync(abs, next);
  }
}

updateReadmeVersion("README.md", /\*\*Current version:\*\* \d+\.\d+\.\d+/, `**Current version:** ${version}`);
updateReadmeVersion(
  "readme-ru.md",
  /\*\*Актуальная версия:\*\* \d+\.\d+\.\d+/,
  `**Актуальная версия:** ${version}`,
);

if (recordRelease) {
  const entries = releaseEntriesFromCommitDates({
    baseVersion,
    commitDates,
    epochDate: versionEpoch,
  });
  const next = renderVersionsMarkdown(entries);
  const prev = fs.existsSync(VERSIONS_FILE) ? fs.readFileSync(VERSIONS_FILE, "utf8") : "";
  if (next !== prev) {
    fs.writeFileSync(VERSIONS_FILE, next);
    console.log(`Updated VERSIONS.md (${entries[0]?.version ?? version})`);
  }
}

console.log(
  `Version: ${version} (${uniqueDays} git day(s) since ${versionEpoch}, ${commitsToday} commit(s) today, ${sha})`,
);
